# Generated by Django 3.2.5 on 2021-07-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='etat',
            field=models.CharField(choices=[('activé', 'activé'), ('désctivé', 'désctivé')], max_length=30),
        ),
    ]
