# Generated by Django 3.2.5 on 2021-07-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_formation_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='categorie',
            field=models.CharField(choices=[('web', 'web'), ('mobile', 'mobile'), ('cloud', 'cloud')], default='web', max_length=30),
        ),
        migrations.AlterField(
            model_name='formation',
            name='etat',
            field=models.CharField(choices=[('activé', 'activé'), ('désactivé', 'désactivé')], default='activé', max_length=30),
        ),
    ]
