# Generated by Django 3.2.5 on 2021-07-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210709_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
