# Generated by Django 3.2.5 on 2021-07-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_formation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='logo',
            field=models.ImageField(upload_to=None),
        ),
    ]
